const infoExp = [
  {
    id: 1,
    link: "https://www.linkedin.com/in/felipejuaneda/details/experience/",
    logo: "https://i.ibb.co/6YBfBJ6/Proyecto-Quitar-fondo.png",
    title: "Desarrollador FullStack",
    description: `Desarrollé una plataforma de aprendizaje en línea utilizando la pila MERN (MongoDB, Express, React, Node.js), que permite a los usuarios registrarse, comprar cursos y acceder a contenido exclusivo. Implementé un sistema de autenticación con JWT y bcrypt, integración con MercadoPago, y funcionalidades internas para usuarios registrados. Usé herramientas como React, Material UI, React Hook Form, Context, Nodemailer, Vite y ESLint.`,
    duration: "abr. 2024 - abr. 2025",
    subtitle: "Prompt The Future · Independiente",
    order: 1,
  },
  {
    id: 2,
    link: "https://www.linkedin.com/in/felipejuaneda/details/experience/",
    logo: "https://flexxus.com.ar/wp-content/uploads/logo-footer-flexxus.png",
    title: "Desarrollador FrontEnd",
    description: `Responsable del desarrollo y mantenimiento de un sistema ERP en Flexxus. Trabajé con React, SQL, Node.js y otras tecnologías bajo la metodología SCRUM. Me enfoqué en nuevas funcionalidades, resolución de bugs y mejoras UX en entornos reales.`,
    duration: "ago. 2024 - feb. 2025",
    subtitle: "Flexxus · Jornada completa",
    order: 2,
  },
  {
    id: 3,
    link: "https://www.linkedin.com/in/felipejuaneda/details/experience/",
    logo: "https://comparte-entity-photos.s3.us-east-2.amazonaws.com/39144702-7af9-45a6-8e18-3eb28648fa8a.png",
    title: "Tutor React Js",
    description: `Tutor principal y adjunto de React en Coderhouse. Realicé dictado de clases, seguimiento de alumnos, respuestas a consultas, corrección de entregas y orientación en el uso de herramientas. Más de 800 entregas corregidas.`,
    duration: "ago. 2022 - ene. 2025",
    subtitle: "Coderhouse · Jornada parcial",
    order: 3,
  },
  {
    id: 4,
    link: "https://www.linkedin.com/in/felipejuaneda/details/experience/",
    logo: "https://i.ibb.co/bsd1Gck/logo-Outside-The-Box-Photoroom-png-Photoroom.png",
    title: "Programador FullStack",
    description: `Desarrollé soluciones para una empresa de logística en Europa, trabajando con Angular, Node.js, PostgreSQL, TypeScript, AWS y GitLab. Actualmente me enfoqué en aplicar IA para mejorar el servicio al cliente.`,
    duration: "mar. 2024 - jun. 2024",
    subtitle: "Outside The Box · Contrato temporal",
    order: 4,
  },
  {
    id: 5,
    link: "https://www.linkedin.com/in/felipejuaneda/details/experience/",
    logo: "https://i.ibb.co/DgX4MGC/Group-41.png",
    title: "Desarrollador FrontEnd",
    description: `Lideré la creación de una plataforma educativa centrada en marca personal, utilizando Next.js, Firebase y Material UI. Me enfoqué en ofrecer una experiencia escalable y visualmente atractiva.`,
    duration: "ene. 2024 - abr. 2024",
    subtitle: "Lemur School · Temporal",
    order: 5,
  },
  {
    id: 6,
    link: "https://www.linkedin.com/in/felipejuaneda/details/experience/",
    logo: "https://i.ibb.co/LgGBjxP/dwilliamsre-logo-Photoroom-png-Photoroom.png",
    title: "Desarrollador FrontEnd",
    description: `Encargado del desarrollo del panel de administración en D' Williams Inmobiliaria. Utilicé Firebase para sincronización en tiempo real y construí una interfaz centrada en eficiencia y colaboración del equipo inmobiliario.`,
    duration: "oct. 2023 - dic. 2023",
    subtitle: "D' Williams Real Estate · Temporal",
    order: 6,
  },
];

export default infoExp;
