const infoExp = [
  {
    id: 1,
    link: "https://www.linkedin.com/in/felipe-juaneda-8b7103190/overlay/1635504432346/single-media-viewer/",
    logo: "https://comparte-entity-photos.s3.us-east-2.amazonaws.com/39144702-7af9-45a6-8e18-3eb28648fa8a.png",
    title: "Tutor React Js",
    description: `En el rol, me encargo del seguimiento constante de los alumnos a lo largo del curso, proporcionando apoyo y clarificaciones sobre los temas tratados en clase. Además, respondo a consultas fuera del horario escolar y corrijo desafíos prácticos de evaluación. Guío a los estudiantes en la realización de sus proyectos finales y ofrezco orientación permanente sobre el uso de herramientas necesarias para su desarrollo académico, habiendo corregido más de 300 entregas hasta la fecha.`,
    duration: "ago. 2022 - act.",
    subtitle: "Coderhouse · Jornada parcial",
    order: 1,
  },
  {
    id: 5,
    link: "https://www.linkedin.com/in/felipejuaneda/",
    logo: "https://i.ibb.co/6YBfBJ6/Proyecto-Quitar-fondo.png",
    title: "Desarrollador FullStack",
    description: `Desarrollé una plataforma de aprendizaje en línea utilizando la pila MERN, que permite a los usuarios registrarse, comprar cursos y acceder a contenido exclusivo. Diseñé la interfaz usando React y Material UI para garantizar un diseño moderno y responsivo. Implementé un sistema de pago a través de MercadoPago y aseguré la autenticación con JWT y bcrypt. En la plataforma interna, accesible solo para usuarios registrados, es posible visualizar y acceder a los cursos adquiridos.`,
    duration: "abr. 2024 - act.",
    subtitle: "Prompt The Future · Independiente",
    order: 2,
  },
  {
    id: 2,
    link: "https://www.linkedin.com/in/felipe-juaneda-8b7103190/",
    logo: "https://i.ibb.co/bsd1Gck/logo-Outside-The-Box-Photoroom-png-Photoroom.png",
    title: "Desarrollador FullStack",
    description: `En el puesto desarrollé y optimicé proyectos para una empresa multinacional de logística que opera en toda Europa. 
Trabajo con un stack tecnológico que incluye Angular, Node.js, PostgreSQL, AWS y GitLab. Actualmente, estoy enfocado en implementar soluciones de inteligencia artificial para mejorar el servicio al cliente.`,
    duration: "mar. 2024 - jun. 2024",
    subtitle: "Outside The Box · Contrato temporal",
    order: 3,
  },
  {
    id: 3,
    link: "https://www.linkedin.com/in/felipe-juaneda-8b7103190/",
    logo: "https://i.ibb.co/DgX4MGC/Group-41.png",
    title: "Desarrollador FrontEnd",
    description: `Como parte del equipo de desarrollo de Lemur School, lideré la creación de una plataforma innovadora que potencia la marca personal de los usuarios, a través de cursos educativos. Utilizando Next.js y Firebase como pilares tecnológicos. Además, implementé Material-UI para ofrecer una experiencia de usuario intuitiva y visualmente atractiva.`,
    duration: "ene. 2024 - abr. 2024",
    subtitle: "Lemur School · Temporal",
    order: 4,
  },
  {
    id: 4,
    link: "https://www.linkedin.com/in/felipe-juaneda-8b7103190/",
    logo: "https://i.ibb.co/LgGBjxP/dwilliamsre-logo-Photoroom-png-Photoroom.png",
    title: "Desarrollador FrontEnd",
    description: `Como encargado del desarrollo del panel de administración en D' Williams Inmobiliaria, lideré la creación del sistema centralizado utilizado por agentes inmobiliarios. La plataforma, integrada con Firebase, ha sido fundamental para facilitar una colaboración eficiente entre los miembros del equipo y permitir la actualización en tiempo real de la extensa cartera de propiedades.`,
    duration: "oct. 2023 - dic. 2023",
    subtitle: "D' Williams · Temporal",
    order: 5,
  },
];
export default infoExp;
